# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty


# Setup
title:               'O.T. Reinert'
tagline:             'Yeet'
description:         'One small step for Oda, two large steps back for mankind'
host:                ''
baseurl:             ''
paginate:            5
