# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty


# Setup
title:               'O.T. Reinert'
tagline:             'Figuring it out'
description:         '"The burden of proof has to be placed on authority... it should be dismantled if that burden cannot be met." - Noam Chomsky'
host:                ''
baseurl:             ''
paginate:            5
