# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty


# Setup
title:               'O.T. Reinert'
tagline:             ':)'
description:         'Figuring it out'
host:                ''
baseurl:             ''
paginate:            5
